# -*- coding: utf-8 -*-
"""Finetune_LLM_empathetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9O3tp_qGeYnafHuy87rzDsrW5Jb3Ett
"""

!pip install wandb

import wandb
wandb.login()

import pandas as pd
import re
import json
from datasets import load_dataset

# Load the dataset from Hugging Face
dataset = load_dataset("usernone1234/capstone-llm-project-SP26AI20")

# dataset.head() # This line caused an AttributeError.
# load_dataset returns a DatasetDict, not a single dataset or dataframe.
# To view the head, access a specific split (e.g., 'train') and convert to pandas.
if 'train' in dataset:
    print("First 5 rows of the 'train' split:")
    print(dataset['train'].to_pandas().head())
elif len(dataset) > 0:
    # If no 'train' split, try the first available split
    first_split_key = list(dataset.keys())[0]
    print(f"No 'train' split found. Displaying first 5 rows of the '{first_split_key}' split:")
    print(dataset[first_split_key].to_pandas().head())
else:
    print("Dataset loaded but no splits found to display.")

# Format instruction
def format_instruction(samples):
  user_queries = samples['user_query']
  emotions = samples['Emotion']
  responses = samples['response']
  texts = []

  for user_query, emotion, response in zip(user_queries, emotions, responses):
    instruction = f"""
    <im_start>system
  Bạn là AI nhận diện cảm xúc trong văn bản tiếng Việt.

  Nhiệm vụ:
  - Xác định cảm xúc của câu người dùng
  - Sau đó phản hồi lại một câu phù hợp với cảm xúc đó

  Các cảm xúc hợp lệ:
  - Buồn bã
  - Lo âu
  - Lạc quan
  - Cô đơn
  - Other
  - Vui vẻ
  - Chán ghét
  - Ngạc nhiên
  - Sợ hãi
  - Tức giận
  - Highly Negative
  - Trung lập
  - Hối tiếc

  Yêu cầu:
  - Trả về JSON
  - Không giải thích
  - Format gồm:
    + emotion: nhãn cảm xúc
    + response: câu phản hồi phù hợp
  <im_end>

  <im_start>user
  {user_query}
  <im_end>

  <im_start>assistant
  {{
    "emotion": "{emotion}",
    "response": "{response}"
  }}
  <im_end>
    """
    texts.append(instruction)
  return {'text': texts}

# Split the 'train' dataset into training and validation sets
train_test_split_dataset = dataset['train'].train_test_split(test_size=0.1, seed=42)

# Call format_instruction on the new 'train' and 'test' (validation) splits
formatted_train_dataset = train_test_split_dataset['train'].map(format_instruction, batched=True)
formatted_validation_dataset = train_test_split_dataset['test'].map(format_instruction, batched=True)

formatted_train_dataset[1]

# Commented out IPython magic to ensure Python compatibility.
# #@title Colab Extra Install { display-mode: "form" }
# %%capture
# import os
# !pip install --upgrade -qqq uv
# if "COLAB_" not in "".join(os.environ.keys()):
#     # If you're not in Colab, just use pip install!
#     !pip install unsloth vllm
# else:
#     try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
#     except: _numpy = "numpy"; _pil = "pillow"
#     try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
#     except: is_t4 = False
#     _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.15.1', 'triton')
#     !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
#     !uv pip install -qqq {_triton}
# !uv pip install transformers==4.56.2
# !uv pip install --no-deps trl==0.22.2

import os
# Attempt to upgrade scipy and numpy to resolve 'KeyError: has ilp64'
# This is done before importing unsloth, as the error occurs during unsloth's initialization.
# A runtime restart might be necessary after running this cell for the changes to fully apply.
try:
    # Assuming 'uv' is installed from the previous cell (S-druyEyvAbi)
    !uv pip install -qqq --upgrade scipy numpy
except Exception as e:
    print(f"Warning: uv failed, trying pip. Error: {e}")
    !pip install -qqq --upgrade scipy numpy

from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 #
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # Changed to True for proper quantization and device placement
    fast_inference = False, # Disable vllm fast inference for troubleshooting
    gpu_memory_utilization = 0.9, # Reduce if out of memory
    device_map = "cuda" # Explicitly map to CUDA
)

# Explicitly set the chat template for the tokenizer
tokenizer.chat_template = (
    "{% for message in messages %}"
        "{% if message['role'] == 'user' %}"
            "{{ '<|im_start|>user\n' + message['content'] + '<|im_end|>\n' }}"
        "{% elif message['role'] == 'system' %}"
            "{{ '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}"
        "{% elif message['role'] == 'assistant' %}"
            "{{ '<|im_start|>assistant\n' + message['content'] + '<|im_end|>\n' }}"
        "{% endif %}"
    "{% endfor %}"
    "{% if add_generation_prompt %}"
        "{{ '<|im_start|>assistant\n' }}"
    "{% endif %}"
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

from trl import SFTTrainer
import math
from transformers import TrainingArguments, TrainerCallback
from unsloth import is_bfloat16_supported

class LoggingCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        # Tính Perplexity từ Training Loss
        if logs is not None and "loss" in logs:
            try:
                logs["perplexity"] = math.exp(logs["loss"])
            except OverflowError:
                logs["perplexity"] = float("inf")

        # Tính Perplexity từ Validation Loss (khi có bước evaluate)
        if logs is not None and "eval_loss" in logs:
            try:
                logs["eval_perplexity"] = math.exp(logs["eval_loss"])
            except OverflowError:
                logs["eval_perplexity"] = float("inf")

wandb.init(
    project = "finetune-llm",
    name = "Qwen2.5-1.5B-Instruct-TamLyVN-v1",
    config = {
        "learning_rate": 2e-4,
        "dataset": "capstone-llm-project-SP26AI20",
    }
)

trainer_sft = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = formatted_train_dataset, # Use the new formatted training dataset
    eval_dataset = formatted_validation_dataset, # Add the formatted validation dataset
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 8,
        eval_strategy="steps",
        eval_steps=15,
        warmup_steps = 10,
        max_steps = 500, # 500 bước để mô hình học sâu hơn các ngõ ngách vấn đề
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs_sft",
        report_to = "wandb",               # Gửi log đến Wandb
        run_name = "qwen2.5-1.5b-sft-v1",  # Tên hiển thị của run
        logging_first_step = True
    ),
    callbacks = [LoggingCallback()]
)

trainer_sft.train()

wandb.finish()

import matplotlib.pyplot as plt
import numpy as np

def plot_training_results(trainer):
    history = trainer.state.log_history

    # 1. Trích xuất dữ liệu Training (thường có key 'loss')
    train_metrics = [x for x in history if 'loss' in x and 'eval_loss' not in x]
    train_loss = [x['loss'] for x in train_metrics]
    train_epochs = [x['epoch'] for x in train_metrics]

    # 2. Trích xuất dữ liệu Validation (thường có key 'eval_loss')
    val_metrics = [x for x in history if 'eval_loss' in x]
    val_loss = [x['eval_loss'] for x in val_metrics]
    val_epochs = [x['epoch'] for x in val_metrics]

    # Kiểm tra nhanh trong console
    print(f"Số điểm dữ liệu Train: {len(train_loss)}")
    print(f"Số điểm dữ liệu Validation: {len(val_loss)}")

    if len(val_loss) == 0:
        print("!!! CẢNH BÁO: Vẫn không thấy eval_loss. Kiểm tra lại eval_steps trong TrainingArguments.")
        # Thử in thử 1 dòng log cuối cùng để debug
        if history: print(f"Dòng log cuối cùng: {history[-1]}")

    plt.figure(figsize=(15, 6))

    # --- Biểu đồ 1: Loss ---
    plt.subplot(1, 2, 1)
    if train_loss:
        plt.plot(train_epochs, train_loss, label='Training Loss', color='#1f77b4', alpha=0.5, linestyle='--')
        # Vẽ thêm đường trung bình trượt (smooth) cho train loss vì nó đang bị zigzag mạnh
        smooth_train = np.convolve(train_loss, np.ones(5)/5, mode='valid')
        plt.plot(train_epochs[4:], smooth_train, color='#1f77b4', lw=2, label='Train Loss (Smooth)')

    if val_loss:
        plt.plot(val_epochs, val_loss, label='Validation Loss', color='#d62728', marker='o', markersize=6, linewidth=2)

    plt.title('Training & Validation Loss', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True, alpha=0.3)

    # --- Biểu đồ 2: Perplexity (PPL) ---
    plt.subplot(1, 2, 2)
    if train_loss:
        plt.plot(train_epochs, np.exp(train_loss), label='Train PPL', color='#2ca02c', alpha=0.4)
    if val_loss:
        plt.plot(val_epochs, np.exp(val_loss), label='Val PPL', color='#ff7f0e', marker='s', markersize=6, linewidth=2)

    plt.title('Perplexity (PPL) over Time', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Score')
    plt.yscale('log') # PPL thường giảm rất nhanh, dùng log scale sẽ dễ nhìn hơn
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

# Gọi hàm
plot_training_results(trainer_sft)

"""# Nhận xét sau evaluate

-------
1. Phân tích đường Validation Loss & PPL (Rất Tốt) Xu hướng giảm ổn định: Đường màu đỏ (Validation Loss) và màu cam (Val PPL) đang đi xuống một cách đều đặn. Đây là dấu hiệu cực kỳ tốt. Nó cho thấy mô hình đang thực sự "học" được kiến thức từ tập dữ liệu và có khả năng áp dụng kiến thức đó lên dữ liệu mới (Validation set) chứ không chỉ học vẹt.Chưa có dấu hiệu Overfitting: Vì đường Validation Loss vẫn đang trên đà đi xuống và chưa có dấu hiệu ngóc đầu lên, nghĩa là bạn có thể train thêm (tăng max_steps) nếu muốn mô hình thông minh hơn nữa.
2. Phân tích đường Training Loss (Cần lưu ý)Biến động cực mạnh (Zigzag): Đường xanh đứt đoạn dao động rất lớn (từ 0.2 đến 0.7). Mặc dù đường trung bình (Smooth) có xu hướng đi ngang hoặc giảm nhẹ, nhưng sự nhiễu này cho thấy việc cập nhật trọng số đang hơi "vất vả".Lý do: Với per_device_train_batch_size = 2 và gradient_accumulation_steps = 4, tổng batch size thực tế của bạn là 8. Đối với các tác vụ yêu cầu logic cao như Luật hay Tâm lý, con số này hơi nhỏ, khiến mô hình bị "giật mình" bởi các mẫu dữ liệu khác nhau.
3. Chỉ số Perplexity (PPL)Con số ấn tượng: PPL của bạn đang nằm ở mức rất thấp (khoảng $1.3 \times 10^0$ đến $1.7 \times 10^0$, tức là quanh mức 1.3 - 1.7).Ý nghĩa: Điều này cực kỳ tốt! Nó cho thấy mô hình dự đoán từ tiếp theo trong tập Validation với độ tự tin rất cao. Với một mô hình nhỏ như Qwen 1.5B hoặc 4B, mức PPL dưới 2 là một kết quả rất hứa hẹn.

# Lưu lại .gguf
"""

# Save it to .gguf
model.save_pretrained_gguf(
    "Qwen2.5-1.5B-Instruct-TamlyVN",               # Tên thư mục lưu trữ
    tokenizer,
    quantization_method = "q4_k_m", # Phương pháp nén (q4_k_m là phổ biến nhất)
)
