# -*- coding: utf-8 -*-
"""PhoBERT_ex_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGDmSeAwYhkuvm2AEA_6lxgJG83AH8BC
"""

!apt-get update
!apt-get install -y openjdk-11-jdk

!wget https://github.com/vncorenlp/VnCoreNLP/archive/refs/heads/master.zip
!unzip master.zip

!pip install datasets
!pip install vncorenlp
!pip install wandb

!pip install huggingface_hub
from huggingface_hub import notebook_login
import wandb

notebook_login()

#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

wandb.login()

# Login lại nếu restart
# !wandb login --relogin

import os
import torch
import torch.nn as nn
import numpy as np
import seaborn as sns
from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoModel,
    TrainingArguments,
    EarlyStoppingCallback,
    Trainer
)
from sklearn.metrics import accuracy_score, f1_score

from datasets import load_dataset

DATASET_NAME = "usernone1234/capstone-llm-project-SP26AI20"

dataset = load_dataset(DATASET_NAME)["train"]

# Giữ lại user_query và Emotion cho PhoBERT
dataset = dataset.select_columns(["user_query", "Emotion"])

print(dataset)

import re
import pandas as pd

clean_teencode_dict = {
    # phổ biến - cần normalize
    "khôg": "không", "hôg": "không", "hok": "không", "ko": "không", "k": "không", "kh": "không", "kô": "không",
    "bik": "biết", "biet": "biết", "biêt": "biết",
    "mih": "mình", "mik": "mình", "mk": "mình", "mjh": "mình",
    "mn": "mọi người", "mng": "mọi người",
    "ng": "người", "ngta": "người ta", "nta": "người ta",
    "bn": "bạn", "bme": "bố mẹ",
    "cx": "cũng", "cũg": "cũng", "kũg": "cũng",
    "vs": "với",
    "đc": "được", "dc": "được", "đươc": "được", "đuợc": "được",
    "z": "vậy", "zậy": "vậy", "zạ": "vậy",
    "ntn": "như thế nào", "nthe": "như thế", "nthế": "như thế", "nvay": "như vậy", "nvậy": "như vậy",
    "trc": "trước", "htrc": "hôm trước",
    "hnay": "hôm nay", "hqua": "hôm qua",
    "ms": "mới",
    "r": "rồi", "oy": "rồi", "zồi": "rồi", "zùi": "rồi",
    "jo": "giờ",
    "ns": "nói",
    "nch": "nói chuyện",
    "lm": "làm",
    "lgi": "làm gì",
    "ntnao": "như thế nào",
    "thjk": "thích", "thik": "thích", "thíc": "thích",
    "iu": "yêu",
    "ny": "người yêu", "nyc": "người yêu cũ",
    "ib": "inbox",
    "kb": "kết bạn",
    "acc": "tài khoản",
    "cviec": "công việc",
    "cty": "công ty",
    "tgian": "thời gian", "thgian": "thời gian",
    "đt": "điện thoại", "đthoai": "điện thoại", "đthoại": "điện thoại",
    "stk": "số tài khoản",
    "sđt": "số điện thoại",
    "gđ": "gia đình", "gđình": "gia đình",
    "bh": "bao giờ", "baoh": "bao giờ",
    "bnhiu": "bao nhiêu", "bnhiêu": "bao nhiêu",
    "qtam": "quan tâm", "qtâm": "quan tâm", "wtâm": "quan tâm",
    "ktra": "kiểm tra",
    "đki": "đăng ký", "đky": "đăng ký", "dky": "đăng ký",
    "vde": "vấn đề", "vđê": "vấn đề",
    "lquan": "liên quan", "klq": "không liên quan",
    "llac": "liên lạc",
    "ctrinh": "chương trình", "ctrình": "chương trình", "ctr": "chương trình",
    "svtn": "sinh viên tình nguyện",
    "sviên": "sinh viên",
    "đhọc": "đại học",
    "thpt": "trung học phổ thông",
    "nvqs": "nghĩa vụ quân sự"
}

# Dấu hiệu Teencode (Ký tự lạ hoặc lặp âm)
teencode_re = r'([a-z])\1{2,}|(vcl|vl|đcm|vãi|uk|uh)'

def classify_query_batch(examples):
    results = []

    for text in examples["user_query"]:
        text_lower = str(text).lower()

        if re.search(teencode_re, text_lower):
            results.append("Teencode")
        elif any(word in text_lower.split() for word in clean_teencode_dict.keys()):
            results.append("Abbreviation")
        else:
            results.append("Standard")

    examples["classify_query"] = results
    return examples

dataset = dataset.map(classify_query_batch, batched=True)

from collections import Counter

counts = Counter(dataset["classify_query"])
print(counts)

def clean_vntk(text):
    text = str(text).lower()

    # 1. normalize teencode
    words = text.split()
    words = [clean_teencode_dict[w] if w in clean_teencode_dict else w for w in words]
    text = " ".join(words)

    # 2. remove special char (giữ ! ?)
    text = re.sub(r'[^a-zA-ZÀ-ỹ0-9!? ]', ' ', text)

    # 3. normalize kéo dài
    text = re.sub(r'([a-z])\1{2,}', r'\1', text)

    return text

def clean_batch(examples):
    examples["user_query"] = [
        clean_vntk(text) for text in examples["user_query"]
    ]
    return examples

# Thực thi làm sạch
dataset = dataset.map(clean_batch, batched=True)

# Gom các nhãn có cảm xúc gần giống nhau
label_groups = {

    # sadness cluster
    'Buồn bã': 'Sadness',
    'Cô đơn': 'Sadness',
    'Hối tiếc': 'Sadness',

    # anxiety / fear cluster
    'Lo âu': 'Anxiety_Fear',
    'Sợ hãi': 'Anxiety_Fear',

    # anger cluster
    'Tức giận': 'Anger',
    'Chán ghét': 'Anger',

    # positive
    'Vui vẻ': 'Positive',
    'Lạc quan': 'Positive',
    'Ngạc nhiên': 'Positive',

    # neutral
    'Trung lập': 'Neutral',
    'Other': 'Neutral',

    # highly neg
    'Highly negative': 'Highly_Negative'
}

def map_coarse(example):
    example["Emotion_coarse"] = label_groups[example["Emotion"]]
    return example

dataset = dataset.map(map_coarse)

# Tạo label2id và id2label cho phobert

from datasets import ClassLabel
# Encode fine
fine_labels = sorted(dataset.unique("Emotion"))
fine_class = ClassLabel(names=fine_labels)

dataset = dataset.cast_column("Emotion", fine_class)

# Encode coarse
coarse_labels = sorted(dataset.unique("Emotion_coarse"))
coarse_class = ClassLabel(names=coarse_labels)

dataset = dataset.cast_column("Emotion_coarse", coarse_class)

# Lấy mapping cho model
label2id_fine = dataset.features["Emotion"]._str2int
id2label_fine = dataset.features["Emotion"]._int2str

label2id_coarse = dataset.features["Emotion_coarse"]._str2int
id2label_coarse = dataset.features["Emotion_coarse"]._int2str

# Word segmentation sử dụng VnCoreNLP
from vncorenlp import VnCoreNLP

# Đường dẫn tới thư mục chứa file jar
rdrsegmenter = VnCoreNLP(
    "VnCoreNLP-master/VnCoreNLP-1.1.1.jar",
    annotators="wseg",
    max_heap_size='-Xmx2g'
)

def word_segment(text):
    sentences = rdrsegmenter.tokenize(text)
    return " ".join([" ".join(sent) for sent in sentences])

def segment_function(examples):
    examples["user_query"] = [word_segment(t) for t in examples["user_query"]]
    return examples

# Áp dụng vào dataset
dataset = dataset.map(segment_function, batched=True)

# Train/Val/Test Split: 0.7-0.15-0.15
# Train
dataset_split = dataset.train_test_split(
    test_size=0.3,
    stratify_by_column="Emotion_coarse",
    seed=42
)

train_dataset = dataset_split["train"]
temp_dataset = dataset_split["test"]

# Test/Val
temp_split = temp_dataset.train_test_split(
    test_size=0.5,
    stratify_by_column="Emotion_coarse",
    seed=42
)

val_dataset = temp_split["train"]
test_dataset = temp_split["test"]

print("Train:", len(train_dataset))
print("Validation:", len(val_dataset))
print("Test:", len(test_dataset))

from transformers import DataCollatorWithPadding

# Tokenization sử dụng PhoBERT
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base", use_fast=False)

def tokenize_function(examples):
    return tokenizer(examples["user_query"], truncation=True, max_length=256)


# Áp dụng vào dataset
train_tokenized = train_dataset.map(tokenize_function, batched=True)\
                              .rename_column("Emotion", "labels_fine")\
                              .rename_column("Emotion_coarse", "labels_coarse")\
                              .remove_columns(["user_query"])

val_tokenized = val_dataset.map(tokenize_function, batched=True)\
                          .rename_column("Emotion", "labels_fine")\
                          .rename_column("Emotion_coarse", "labels_coarse")\
                          .remove_columns(["user_query"])

test_tokenized = test_dataset.map(tokenize_function, batched=True)\
                           .rename_column("Emotion", "labels_fine")\
                           .rename_column("Emotion_coarse", "labels_coarse")\
                           .remove_columns(["user_query"])

# 5: Format for PyTorch
train_tokenized.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels_fine", "labels_coarse"]
)

val_tokenized.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels_fine", "labels_coarse"]
)

test_tokenized.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels_fine", "labels_coarse"]
)

class PhoBERTMultiHead(nn.Module):
    def __init__(self, model_name, num_fine, num_coarse):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        hidden_size = self.encoder.config.hidden_size

        # Thêm tầng đệm
        self.dense = nn.Linear(hidden_size, hidden_size)
        self.activation = nn.Tanh() # Giúp mô hình học các biểu diễn phi tuyến tính
        self.dropout = nn.Dropout(0.1)

        # Classification heads
        self.classifier_fine = nn.Linear(hidden_size, num_fine)
        self.classifier_coarse = nn.Linear(hidden_size, num_coarse)

        # # Biến học cho Dynamic Loss Weighting
        # self.log_vars = nn.Parameter(torch.zeros(2))

    def forward(self, input_ids, attention_mask, labels_fine=None, labels_coarse=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)

        # Tối ưu trích xuất đặc trưng: Dùng pooler_output nếu có, nếu không thì dùng CLS token
        if hasattr(outputs, 'pooler_output') and outputs.pooler_output is not None:
            pooled = outputs.pooler_output
        else:
            pooled = outputs.last_hidden_state[:, 0]

        # Tầng đệm
        pooled = self.dropout(pooled)
        pooled = self.dense(pooled)
        pooled = self.activation(pooled)
        pooled = self.dropout(pooled)

        # Tính logits
        logits_fine = self.classifier_fine(pooled)
        logits_coarse = self.classifier_coarse(pooled)

        loss = None
        if labels_fine is not None and labels_coarse is not None:

            # Label smoothing (do label gộp bị mất cân bằng)
            loss_fct = nn.CrossEntropyLoss(label_smoothing=0.1)

            loss_fine = loss_fct(logits_fine, labels_fine)
            loss_coarse = loss_fct(logits_coarse, labels_coarse)

            # # Dynamic Uncertainty Weighting (bị catastrophic forgetting)
            # # Công thức: Loss = exp(-log_var) * Task_Loss + log_var
            # # Mô hình sẽ tự động tìm tỷ lệ hoàn hảo giữa Fine và Coarse thay vì fix cứng
            # loss_0 = torch.exp(-self.log_vars[0]) * loss_fine + self.log_vars[0]
            # loss_1 = torch.exp(-self.log_vars[1]) * loss_coarse + self.log_vars[1]

            # loss = loss_0 + loss_1

            loss = 0.7 * loss_fine + 0.3 * loss_coarse

        return {
            "loss": loss,
            "logits": (logits_fine, logits_coarse)
        }

from transformers import TrainerCallback

class WandbCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            wandb.log(logs)

class MultiTaskTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # 2 input
        labels_fine = inputs.get("labels_fine")
        labels_coarse = inputs.get("labels_coarse")

        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            labels_fine=labels_fine,
            labels_coarse=labels_coarse
        )

        loss = outputs["loss"]

        return (loss, outputs) if return_outputs else loss

# Data collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # predictions là tuple nếu bạn return nhiều logits
    logits_fine, logits_coarse = predictions
    labels_fine, labels_coarse = labels

    # Lấy class dự đoán
    preds_fine = logits_fine.argmax(axis=-1)
    preds_coarse = logits_coarse.argmax(axis=-1)

    # ===== Fine metrics =====
    acc_fine = accuracy_score(labels_fine, preds_fine)
    f1_fine_macro = f1_score(labels_fine, preds_fine, average="macro")
    f1_fine_weighted = f1_score(labels_fine, preds_fine, average="weighted")

    # ===== Coarse metrics =====
    acc_coarse = accuracy_score(labels_coarse, preds_coarse)
    f1_coarse_macro = f1_score(labels_coarse, preds_coarse, average="macro")

    return {
        "accuracy_fine": acc_fine,
        "f1_fine_macro": f1_fine_macro,
        "f1_fine_weighted": f1_fine_weighted,

        "accuracy_coarse": acc_coarse,
        "f1_coarse_macro": f1_coarse_macro,
    }

# init wandb
wandb.init(
    project="PhoBERT_ex",
    name="MultiheadModel_final"
)

model = PhoBERTMultiHead("vinai/phobert-large", len(label2id_fine), len(label2id_coarse))

training_args = TrainingArguments(
    output_dir="./phobert-multitask",
    learning_rate=1e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=8,

    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="eval_accuracy_fine",
    greater_is_better=True,

    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    weight_decay=0.01,

    report_to="wandb",
)

trainer = MultiTaskTrainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    compute_metrics=compute_metrics,
    data_collator=data_collator,
    callbacks=[WandbCallback(), EarlyStoppingCallback(early_stopping_patience=3)]
)

trainer.train()

trainer.evaluate(test_tokenized)

wandb.finish()

def log_confusion_matrix(
    y_true,
    y_pred,
    class_names,
    title="Confusion Matrix",
    normalize=True,
    log_wandb=True
):
    # ===== 1. Compute CM =====
    cm = confusion_matrix(
        y_true,
        y_pred,
        normalize="true" if normalize else None
    )

    # ===== 2. Plot =====
    plt.figure(figsize=(12, 10))

    sns.heatmap(
        cm,
        annot=True,
        fmt=".2f" if normalize else "d",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names,
        cbar_kws={'label': 'Proportion' if normalize else 'Count'}
    )

    plt.title(title)
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")

    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)

    plt.tight_layout()

    # ===== 3. Log to wandb =====
    if log_wandb:
        wandb.log({title: wandb.Image(plt)})

    plt.show()
    plt.close()

# init wandb
wandb.init(
    project="PhoBERT_ex",
    name="MultiheadModel_report_final"
)

def get_predictions(trainer, dataset):
    # Lấy output từ trainer
    predictions, _, _ = trainer.predict(dataset)

    # Custom model trả về tuple (logits_fine, logits_coarse)
    logits_fine, logits_coarse = predictions

    # Lấy nhãn dự đoán (argmax)
    preds_fine = np.argmax(logits_fine, axis=1)
    preds_coarse = np.argmax(logits_coarse, axis=1)

    # Lấy nhãn thực tế từ dataset
    labels_fine = dataset["labels_fine"]
    labels_coarse = dataset["labels_coarse"]

    return preds_fine, preds_coarse, labels_fine, labels_coarse

preds_fine, preds_coarse, labels_fine, labels_coarse = get_predictions(trainer, test_tokenized)

fine_label_names = [
    "Buồn bã",
    "Cô đơn",
    "Hối tiếc",
    "Lo âu",
    "Sợ hãi",
    "Tức giận",
    "Chán ghét",
    "Vui vẻ",
    "Lạc quan",
    "Ngạc nhiên",
    "Trung lập",
    "Other",
    "Highly negative"
]

coarse_label_names = [
    "Sadness",
    "Anxiety_Fear",
    "Anger",
    "Positive",
    "Neutral",
    "Highly_Negative"
]


log_confusion_matrix(labels_fine, preds_fine, fine_label_names, "Confusion Matrix Fine")
log_confusion_matrix(labels_coarse, preds_coarse, coarse_label_names, "Confusion Matrix Coarse")

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from datasets import Dataset

# 1. Định nghĩa dữ liệu test (Dựa trên list bạn cung cấp)
test_data = [
    ("Tui bùn mún khóc lun á, hông ai hỉu tui hết...", "Negative_Sad", "Buồn bã"),
    ("Cái thói làm ăn vầy là tui chán ghét cực kì nha", "Negative_Sad", "Chán ghét"),
    ("Ngồi 1 mình giữa phố đông, thấy cô đơn vcl", "Negative_Sad", "Cô đơn"),
    ("Giá như hùi đó mình ko làm v, hối tiếc ghê", "Negative_Sad", "Hối tiếc"),
    ("Lo wá, ko bít mai đi thi có ổn áp ko nữa", "Negative_Sad", "Lo âu"),
    ("Trời ơi hnay tui zui quá xá là zui lunnn", "Positive", "Vui vẻ"),
    ("Mọi chuyện rùi sẽ ổn thui, cố lên tui ơi!", "Positive", "Lạc quan"),
    ("Wao, ko thể tin đc lun, bất ngờ thực sự!", "Surprise", "Ngạc nhiên"),
    ("Đm làm ăn như cc, bực cả mình, mún đấm ghê", "Anger", "Tức giận"),
    ("Sợ vcl, chỗ này nhìn âm u ghê rợn quá", "Fear", "Sợ hãi"),
    ("Cũng bth thui, ko có gì đặc biệt lắm", "Neutral_Other", "Trung lập"),
    ("Ủa alo, cái gì đang xảy ra v mọi người?", "Neutral_Other", "Other")
]

# 2. Xử lý dữ liệu
processed_data = {
    'input_ids': [],
    'attention_mask': [],
    'labels_fine': [],
    'labels_coarse': [],
    'text': [],
    'true_fine': [],
    'true_coarse': []
}

for text, true_coarse, true_fine in test_data:
    # Tiền xử lý
    cleaned = clean_vntk(text)
    segmented = word_segment(cleaned)

    # Tokenize
    tokenized = tokenizer(segmented, truncation=True, padding='max_length', max_length=256, return_tensors="pt")

    processed_data['input_ids'].append(tokenized['input_ids'].squeeze().tolist())
    processed_data['attention_mask'].append(tokenized['attention_mask'].squeeze().tolist())
    processed_data['labels_fine'].append(0)   # Dummy
    processed_data['labels_coarse'].append(0) # Dummy
    processed_data['text'].append(text)
    processed_data['true_fine'].append(true_fine)
    processed_data['true_coarse'].append(true_coarse)

# Chuyển sang HuggingFace Dataset
predict_dataset = Dataset.from_pandas(pd.DataFrame(processed_data))
predict_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels_fine", "labels_coarse"])

# 3. Dự đoán
predictions_output = trainer.predict(predict_dataset)
logits_fine = predictions_output.predictions[0]
logits_coarse = predictions_output.predictions[1]

predicted_fine_ids = logits_fine.argmax(axis=-1)
predicted_coarse_ids = logits_coarse.argmax(axis=-1)

# 4. Hiển thị kết quả so sánh
results = []
for i in range(len(test_data)):
    pred_fine = id2label_fine[predicted_fine_ids[i].item()]
    pred_coarse = id2label_coarse[predicted_coarse_ids[i].item()]

    results.append({
        "Câu gốc": processed_data['text'][i],
        "Dự đoán (Fine)": pred_fine,
        "Thực tế (Fine)": processed_data['true_fine'][i],
        "Dự đoán (Coarse)": pred_coarse,
        "Thực tế (Coarse)": processed_data['true_coarse'][i],
        "Kết quả": "✅" if pred_fine == processed_data['true_fine'][i] else "❌"
    })

# In bảng kết quả
df_results = pd.DataFrame(results)
print(df_results.to_string(index=False))

# Tính độ chính xác nhanh
accuracy = sum(1 for r in results if r["Kết quả"] == "✅") / len(results)
print(f"\nOverall Accuracy (Fine-grained): {accuracy * 100:.2f}%")