# -*- coding: utf-8 -*-
"""Speech_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBANO3UpUOM3M5S3c-nLkvKw-lLIrr0z
"""

!nvidia-smi

!pip install -q --upgrade pip

!pip install -q \
  transformers==4.46.3 \
  datasets==3.1.0 \
  evaluate==0.4.3 \
  jiwer==3.0.5 \
  librosa==0.10.2.post1 \
  accelerate==1.1.1 \
  peft==0.13.2 \
  huggingface_hub==0.26.2 \
  numpy==2.0.2 \
  pandas==2.2.2 \
  soundfile==0.12.1 \
  sentencepiece==0.2.0 \
  scikit-learn==1.5.2 \
  numba==0.60.0 \
  matplotlib==3.9.2 \
  seaborn

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import jiwer
import shutil
import torch
import librosa
import evaluate
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from difflib import SequenceMatcher
from collections import Counter
from dataclasses import dataclass
from typing import Any, Dict, List, Union
from transformers import EarlyStoppingCallback
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

from datasets import load_dataset, DatasetDict, load_from_disk, Audio
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)
from transformers.trainer_utils import get_last_checkpoint
from transformers.utils import logging

warnings.filterwarnings(
    "ignore",
    message="Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead."
)
warnings.filterwarnings(
    "ignore",
    message="Passing a tuple of `past_key_values` is deprecated"
)

logging.set_verbosity_error()

# ----- DATA SOURCE -----
HF_DATASET_REPO = "usernone1234/audio_clean_dataset"

# ----- LOCAL SAVE PATHS -----
FILTERED_DATASET_DIR = "/content/drive/MyDrive/Youtube_Transcripts_Final/filtered_dataset"
OUTPUT_DIR = "/content/drive/MyDrive/Youtube_Transcripts_Final/whisper_vi_finetuned"
FINAL_MODEL_DIR = "/content/drive/MyDrive/Youtube_Transcripts_Final/whisper_vi_final_model"
PROCESSED_DATASET_DIR = "/content/processed_whisper_dataset"

# ----- MODEL CONFIG -----
BASE_MODEL = "openai/whisper-small"
LANGUAGE = "vi"
TASK = "transcribe"

# ----- LORA CONFIG -----
USE_LORA = True
LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "out_proj"]

# ----- TRAIN CONFIG -----
TRAIN_BATCH_SIZE = 4
EVAL_BATCH_SIZE = 4
GRAD_ACCUM_STEPS = 8
LEARNING_RATE = 1e-4
MAX_STEPS = 2000
WARMUP_STEPS = 100
LOGGING_STEPS = 25
EVAL_STEPS = 200
SAVE_STEPS = 200
SAVE_TOTAL_LIMIT = 2
MAX_AUDIO_SEC = 30
SEED = 42

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(FINAL_MODEL_DIR, exist_ok=True)

print("HF_DATASET_REPO:", HF_DATASET_REPO)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("FINAL_MODEL_DIR:", FINAL_MODEL_DIR)

def load_processor_and_model():
    processor = WhisperProcessor.from_pretrained(
        BASE_MODEL,
        language=LANGUAGE,
        task=TASK
    )

    model = WhisperForConditionalGeneration.from_pretrained(BASE_MODEL)

    model.config.use_cache = False
    model.generation_config.language = LANGUAGE
    model.generation_config.task = TASK
    model.generation_config.forced_decoder_ids = processor.get_decoder_prompt_ids(
        language=LANGUAGE,
        task=TASK
    )
    model.generation_config.suppress_tokens = []

    if USE_LORA:
        lora_config = LoraConfig(
            r=LORA_R,
            lora_alpha=LORA_ALPHA,
            target_modules=LORA_TARGET_MODULES,
            lora_dropout=LORA_DROPOUT,
            bias="none"
        )

        model.enable_input_require_grads()
        model = get_peft_model(model, lora_config)

        print("\n===== LORA PARAM CHECK =====")
        model.print_trainable_parameters()

    return processor, model

"""# PHA A - LOAD DATASET FROM HUGGING FACE / SAVE DATASET"""

dataset_raw = load_dataset(HF_DATASET_REPO)

# nếu repo chỉ có 1 split train
if "train" in dataset_raw:
    hf_ds = dataset_raw["train"]
else:
    first_split = list(dataset_raw.keys())[0]
    hf_ds = dataset_raw[first_split]

print(hf_ds)
print("Columns:", hf_ds.column_names)

# đổi text -> sentence để giữ tương thích code cũ
if "text" in hf_ds.column_names and "sentence" not in hf_ds.column_names:
    hf_ds = hf_ds.rename_column("text", "sentence")

# Chuẩn hóa transcript trước khi train
import re
import unicodedata

def normalize_text_train(text):
    text = "" if text is None else str(text)
    text = text.strip().lower()
    text = unicodedata.normalize("NFC", text)
    text = re.sub(r"\s+", " ", text)
    return text

def normalize_sentence_example(example):
    example["sentence"] = normalize_text_train(example["sentence"])
    return example

hf_ds = hf_ds.map(normalize_sentence_example)

print("Sample normalized transcripts:")
for i in range(min(5, len(hf_ds))):
    print(f"{i}: {hf_ds[i]['sentence']}")

# chỉ giữ 2 cột cần thiết
keep_cols = ["audio", "sentence"]
drop_cols = [c for c in hf_ds.column_names if c not in keep_cols]
if drop_cols:
    hf_ds = hf_ds.remove_columns(drop_cols)

hf_ds = hf_ds.cast_column("audio", Audio(sampling_rate=16000))

# split train / validation / test
tmp = hf_ds.train_test_split(test_size=0.1, seed=SEED)
train_ds = tmp["train"]
valid_test_ds = tmp["test"]

tmp2 = valid_test_ds.train_test_split(test_size=0.5, seed=SEED)
valid_ds = tmp2["train"]
test_ds = tmp2["test"]

dataset = DatasetDict({
    "train": train_ds,
    "validation": valid_ds,
    "test": test_ds
})

def is_valid_example(example):
    try:
        text = example["sentence"]
        audio = example["audio"]

        if text is None or len(str(text).strip()) == 0:
            return False

        arr = audio["array"]
        sr = audio["sampling_rate"]
        duration = len(arr) / sr

        return 0 < duration <= MAX_AUDIO_SEC
    except Exception:
        return False

dataset = dataset.filter(is_valid_example)

# save filtered dataset
dataset.save_to_disk(FILTERED_DATASET_DIR)
print("Saved filtered dataset to:", FILTERED_DATASET_DIR)

# 8) Load model/processor để prepare features
processor = WhisperProcessor.from_pretrained(
    BASE_MODEL,
    language=LANGUAGE,
    task=TASK
)

def prepare_dataset(batch):
    audio = batch["audio"]

    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    ).input_features[0]

    batch["labels"] = processor.tokenizer(
        batch["sentence"],
        truncation=True
    ).input_ids

    return batch

dataset_processed = dataset.map(
    prepare_dataset,
    remove_columns=dataset["train"].column_names,
    num_proc=1
)

# 9) Save processed dataset (output chính của pha A)
if os.path.exists(PROCESSED_DATASET_DIR):
    shutil.rmtree(PROCESSED_DATASET_DIR)

dataset_processed.save_to_disk(PROCESSED_DATASET_DIR)
print("Saved processed dataset to:", PROCESSED_DATASET_DIR)

"""# PHA B - LOAD PROCESSED FOLDER / BUILD TRAINER / SAVE SETUP"""

# 1) Load folder của pha B
if os.path.exists(PROCESSED_DATASET_DIR):
    dataset_processed = load_from_disk(PROCESSED_DATASET_DIR)
    print("Loaded processed dataset from local Colab:", PROCESSED_DATASET_DIR)
else:
    print("Processed dataset not found in /content. Rebuilding from filtered dataset...")

    dataset = load_from_disk(FILTERED_DATASET_DIR)

    dataset_processed = dataset.map(
        prepare_dataset,
        remove_columns=dataset["train"].column_names,
        num_proc=1
    )

    dataset_processed.save_to_disk(PROCESSED_DATASET_DIR)
    print("Rebuilt and saved processed dataset to:", PROCESSED_DATASET_DIR)

print(dataset_processed)

# 2) Load processor/model
processor, model = load_processor_and_model()
model.config.use_cache = False
model.generation_config.task = TASK
model.generation_config.language = LANGUAGE
model.generation_config.forced_decoder_ids = processor.get_decoder_prompt_ids(
    language=LANGUAGE,
    task=TASK
)

# 3) Data collator
@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": f["input_features"]} for f in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")

        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        if (labels[:, 0] == self.processor.tokenizer.bos_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels
        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

text_norm = jiwer.Compose([
    jiwer.ToLowerCase(),
    jiwer.RemoveMultipleSpaces(),
    jiwer.Strip(),
])

def normalize_text_list(texts):
    return [text_norm(t) for t in texts]

def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids.copy()

    if isinstance(pred_ids, tuple):
        pred_ids = pred_ids[0]

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    pred_str = normalize_text_list(pred_str)
    label_str = normalize_text_list(label_str)

    return {
        "wer": wer_metric.compute(predictions=pred_str, references=label_str),
        "cer": cer_metric.compute(predictions=pred_str, references=label_str)
    }

# 5) Training args + trainer
training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=EVAL_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM_STEPS,
    learning_rate=LEARNING_RATE,
    warmup_steps=WARMUP_STEPS,
    max_steps=MAX_STEPS,
    gradient_checkpointing=True,
    fp16=torch.cuda.is_available(),
    fp16_full_eval=False,
    evaluation_strategy="steps",      # hoặc "epoch"
    save_strategy="steps",            # phải khớp với evaluation_strategy
    eval_steps=EVAL_STEPS,
    save_steps=EVAL_STEPS,
    logging_steps=LOGGING_STEPS,
    predict_with_generate=True,
    generation_max_length=225,
    load_best_model_at_end=True,
    metric_for_best_model="wer",      # theo dõi WER
    greater_is_better=False,          # vì WER càng thấp càng tốt
    save_total_limit=2,
    report_to="none",
    remove_unused_columns=False
)

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=dataset_processed["train"],
    eval_dataset=dataset_processed["validation"],
    data_collator=data_collator,
    processing_class=processor,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

# 6) Save setup cuối pha B
trainer.save_model(OUTPUT_DIR)
processor.save_pretrained(OUTPUT_DIR)
print("Saved phase B setup to:", OUTPUT_DIR)

"""# PHA C - LOAD OUTPUT FOLDER / TRAIN / EVAL / SAVE FINAL MODEL"""

# 1) Load folder/output của pha C
if os.path.exists(PROCESSED_DATASET_DIR):
    dataset_processed = load_from_disk(PROCESSED_DATASET_DIR)
    print("Loaded processed dataset from local Colab:", PROCESSED_DATASET_DIR)
else:
    print("Processed dataset not found in /content. Rebuilding from filtered dataset...")

    dataset = load_from_disk(FILTERED_DATASET_DIR)

    dataset_processed = dataset.map(
        prepare_dataset,
        remove_columns=dataset["train"].column_names,
        num_proc=1
    )

    dataset_processed.save_to_disk(PROCESSED_DATASET_DIR)
    print("Rebuilt and saved processed dataset to:", PROCESSED_DATASET_DIR)

processor, model = load_processor_and_model()

best_ckpt = None
if os.path.exists(OUTPUT_DIR):
    best_ckpt = get_last_checkpoint(OUTPUT_DIR)

if USE_LORA:
    base_model = WhisperForConditionalGeneration.from_pretrained(BASE_MODEL)

    # nếu trainer đã train xong, ưu tiên best checkpoint
    ckpt_path = trainer.state.best_model_checkpoint if trainer.state.best_model_checkpoint else OUTPUT_DIR
    print("Loading eval model from:", ckpt_path)

    eval_model = PeftModel.from_pretrained(base_model, ckpt_path)
else:
    ckpt_path = trainer.state.best_model_checkpoint if trainer.state.best_model_checkpoint else OUTPUT_DIR
    print("Loading eval model from:", ckpt_path)

    eval_model = WhisperForConditionalGeneration.from_pretrained(ckpt_path)

eval_model.config.use_cache = True
eval_model.generation_config.language = LANGUAGE
eval_model.generation_config.task = TASK
eval_model.generation_config.forced_decoder_ids = processor.get_decoder_prompt_ids(
    language=LANGUAGE,
    task=TASK
)

eval_model.to(trainer.args.device)

# Rebuild trainer để đảm bảo chạy độc lập theo pha
data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=dataset_processed["train"],
    eval_dataset=dataset_processed["validation"],
    data_collator=data_collator,
    processing_class=processor,
    compute_metrics=compute_metrics
)

# Fix resume checkpoint
import numpy.core.multiarray
torch.serialization.add_safe_globals([
    numpy.core.multiarray._reconstruct,
    np.ndarray,
    np.dtype,
    type(np.dtype(np.float32)),
    type(np.dtype(np.uint32)),
])

# 2) Resume train nếu có checkpoint
last_checkpoint = get_last_checkpoint(OUTPUT_DIR)
print("Last checkpoint:", last_checkpoint)

if last_checkpoint:
    print("Resuming from checkpoint...")
    trainer.train(resume_from_checkpoint=True)
else:
    print("Training from scratch...")
    trainer.train()

# 3) Save model sau train
trainer.save_model(OUTPUT_DIR)
processor.save_pretrained(OUTPUT_DIR)
print("Saved trained model to:", OUTPUT_DIR)

# 4) Load model tốt nhất để evaluate/infer
from copy import deepcopy

print("Best checkpoint:", trainer.state.best_model_checkpoint)

eval_model.to(trainer.args.device)

eval_args = deepcopy(trainer.args)
eval_args.fp16 = False
eval_args.fp16_full_eval = False
eval_args.predict_with_generate = True
eval_args.generation_max_length = 160

eval_trainer = Seq2SeqTrainer(
    args=eval_args,
    model=eval_model,
    train_dataset=dataset_processed["train"],
    eval_dataset=dataset_processed["validation"],
    data_collator=data_collator,
    processing_class=processor,
    compute_metrics=compute_metrics
)

val_metrics = eval_trainer.evaluate(eval_dataset=dataset_processed["validation"])
test_metrics = eval_trainer.evaluate(eval_dataset=dataset_processed["test"])

print("\nValidation metrics:", val_metrics)
print("Test metrics:", test_metrics)

# 5) Log training
log_df = pd.DataFrame(trainer.state.log_history)

print("===== Train Log Table =====")
train_logs = log_df[log_df["loss"].notna()].copy()
print(train_logs[["step", "epoch", "learning_rate", "grad_norm", "loss"]].head(10))

print("\n===== Eval Log Table =====")
eval_logs = log_df[log_df["eval_loss"].notna()].copy()
if not eval_logs.empty:
    print(eval_logs[[
        "step", "epoch", "eval_loss", "eval_wer", "eval_cer",
        "eval_runtime", "eval_samples_per_second", "eval_steps_per_second"
    ]])
else:
    print("No eval logs found.")

# ===== Plot Loss =====
plt.figure(figsize=(10, 5))

if not train_logs.empty:
    plt.plot(train_logs["step"], train_logs["loss"], label="train_loss")

if not eval_logs.empty:
    plt.plot(eval_logs["step"], eval_logs["eval_loss"], label="eval_loss")

plt.xlabel("Step")
plt.ylabel("Loss")
plt.title("Training / Evaluation Loss")
plt.legend()
plt.grid(True)
plt.show()

# ===== Plot WER =====
if not eval_logs.empty and "eval_wer" in eval_logs.columns:
    plt.figure(figsize=(10, 5))
    plt.plot(eval_logs["step"], eval_logs["eval_wer"])
    plt.xlabel("Step")
    plt.ylabel("WER")
    plt.title("Evaluation WER")
    plt.grid(True)
    plt.show()

# ===== Plot CER =====
if not eval_logs.empty and "eval_cer" in eval_logs.columns:
    plt.figure(figsize=(10, 5))
    plt.plot(eval_logs["step"], eval_logs["eval_cer"])
    plt.xlabel("Step")
    plt.ylabel("CER")
    plt.title("Evaluation CER")
    plt.grid(True)
    plt.show()

# 6) Predict test
import re
import unicodedata

def normalize_text_for_metric(text):
    text = "" if text is None else str(text)
    text = text.strip().lower()
    text = unicodedata.normalize("NFC", text)
    text = re.sub(r"\s+", " ", text)
    return text

pred_output = eval_trainer.predict(dataset_processed["test"])

pred_ids = pred_output.predictions
label_ids = pred_output.label_ids.copy()

if isinstance(pred_ids, tuple):
    pred_ids = pred_ids[0]

pred_ids = np.array(pred_ids)
label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

pred_texts = processor.tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
label_texts = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

# normalized texts for fairer metric comparison
pred_texts_norm = [normalize_text_for_metric(x) for x in pred_texts]
label_texts_norm = [normalize_text_for_metric(x) for x in label_texts]

for i in range(min(5, len(pred_texts))):
    print(f"\n--- SAMPLE {i} ---")
    print("REF_RAW  :", label_texts[i])
    print("PRED_RAW :", pred_texts[i])
    print("REF_NORM :", label_texts_norm[i])
    print("PRED_NORM:", pred_texts_norm[i])

# 7) Per-sample WER/CER + summary + worst samples (raw + normalized)
df = pd.DataFrame({
    "reference": label_texts,
    "prediction": pred_texts,
    "reference_norm": label_texts_norm,
    "prediction_norm": pred_texts_norm
}).copy()

# raw metrics
raw_wers = []
raw_cers = []

for gt, pred in zip(df["reference"], df["prediction"]):
    gt = "" if pd.isna(gt) else str(gt)
    pred = "" if pd.isna(pred) else str(pred)
    raw_wers.append(jiwer.wer(gt, pred))
    raw_cers.append(jiwer.cer(gt, pred))

df["WER_raw"] = raw_wers
df["CER_raw"] = raw_cers

# normalized metrics
norm_wers = []
norm_cers = []

for gt, pred in zip(df["reference_norm"], df["prediction_norm"]):
    gt = "" if pd.isna(gt) else str(gt)
    pred = "" if pd.isna(pred) else str(pred)
    norm_wers.append(jiwer.wer(gt, pred))
    norm_cers.append(jiwer.cer(gt, pred))

df["WER_norm"] = norm_wers
df["CER_norm"] = norm_cers

summary = pd.DataFrame({
    "Metric": ["WER_raw", "CER_raw", "WER_norm", "CER_norm"],
    "Mean": [
        np.mean(df["WER_raw"]),
        np.mean(df["CER_raw"]),
        np.mean(df["WER_norm"]),
        np.mean(df["CER_norm"])
    ],
    "Std": [
        np.std(df["WER_raw"]),
        np.std(df["CER_raw"]),
        np.std(df["WER_norm"]),
        np.std(df["CER_norm"])
    ],
    "Min": [
        np.min(df["WER_raw"]),
        np.min(df["CER_raw"]),
        np.min(df["WER_norm"]),
        np.min(df["CER_norm"])
    ],
    "Max": [
        np.max(df["WER_raw"]),
        np.max(df["CER_raw"]),
        np.max(df["WER_norm"]),
        np.max(df["CER_norm"])
    ]
})

summary[["Mean", "Std", "Min", "Max"]] = summary[["Mean", "Std", "Min", "Max"]].round(6)

print("\n===== Final Evaluation (Test Set) =====")
display(summary)

print("\n===== Sample-level Results =====")
display(df[[
    "reference", "prediction",
    "reference_norm", "prediction_norm",
    "WER_raw", "CER_raw", "WER_norm", "CER_norm"
]].head(10))

print("\n===== Worst Samples by WER_raw =====")
display(
    df.sort_values("WER_raw", ascending=False)[[
        "reference", "prediction",
        "WER_raw", "CER_raw",
        "WER_norm", "CER_norm"
    ]].head(10)
)

print("\n===== Worst Samples by WER_norm =====")
display(
    df.sort_values("WER_norm", ascending=False)[[
        "reference", "prediction",
        "reference_norm", "prediction_norm",
        "WER_raw", "CER_raw",
        "WER_norm", "CER_norm"
    ]].head(10)
)

# 8) Save predictions
result_df = pd.DataFrame({
    "reference": label_texts,
    "prediction": pred_texts,
    "reference_norm": label_texts_norm,
    "prediction_norm": pred_texts_norm
})

pred_csv_path = os.path.join(OUTPUT_DIR, "test_predictions.csv")
result_df.to_csv(pred_csv_path, index=False, encoding="utf-8-sig")
print("Saved predictions to:", pred_csv_path)

# 9) Confusion matrix ký tự
def normalize_text_for_cm(text):
    return text.strip().lower()

def align_texts_char_level(ref, hyp):
    ref = normalize_text_for_cm(ref)
    hyp = normalize_text_for_cm(hyp)

    matcher = SequenceMatcher(None, ref, hyp)
    aligned_ref = []
    aligned_hyp = []

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        ref_chunk = ref[i1:i2]
        hyp_chunk = hyp[j1:j2]

        if tag == "equal":
            aligned_ref.extend(list(ref_chunk))
            aligned_hyp.extend(list(hyp_chunk))

        elif tag == "replace":
            max_len = max(len(ref_chunk), len(hyp_chunk))
            ref_chunk = ref_chunk.ljust(max_len, "∅")
            hyp_chunk = hyp_chunk.ljust(max_len, "∅")
            aligned_ref.extend(list(ref_chunk))
            aligned_hyp.extend(list(hyp_chunk))

        elif tag == "delete":
            aligned_ref.extend(list(ref_chunk))
            aligned_hyp.extend(["∅"] * len(ref_chunk))

        elif tag == "insert":
            aligned_ref.extend(["∅"] * len(hyp_chunk))
            aligned_hyp.extend(list(hyp_chunk))

    return aligned_ref, aligned_hyp

all_ref_chars, all_pred_chars = [], []

for ref, hyp in zip(label_texts, pred_texts):
    r, h = align_texts_char_level(ref, hyp)
    all_ref_chars.extend(r)
    all_pred_chars.extend(h)

# lấy top ký tự thật từ reference, bỏ ký tự trống/padding
counter = Counter([c for c in all_ref_chars if c not in ["∅"] and c.strip() != ""])
top_chars = [c for c, _ in counter.most_common(30)]
top_chars = sorted(set(top_chars))

filtered_ref, filtered_pred = [], []
for r, p in zip(all_ref_chars, all_pred_chars):
    if r in top_chars and p in top_chars:
        filtered_ref.append(r)
        filtered_pred.append(p)

print("Số cặp ký tự dùng để vẽ confusion matrix:", len(filtered_ref))

if len(filtered_ref) == 0:
    print("Không có đủ cặp ký tự hợp lệ để vẽ confusion matrix.")
else:
    cm = confusion_matrix(filtered_ref, filtered_pred, labels=top_chars, normalize="true")

    plt.figure(figsize=(14, 12))
    sns.heatmap(
        cm,
        annot=True,
        fmt=".2f",
        cmap="Blues",
        xticklabels=top_chars,
        yticklabels=top_chars,
        cbar_kws={"label": "Proportion"}
    )
    plt.title("Character-level Confusion Matrix (Aligned)")
    plt.xlabel("Predicted Character")
    plt.ylabel("True Character")
    plt.xticks(rotation=45, ha="right")
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

# 10) Save final model cuối pha C
if USE_LORA:
    merged_model = eval_model.merge_and_unload()
    merged_model.save_pretrained(FINAL_MODEL_DIR)
else:
    eval_model.save_pretrained(FINAL_MODEL_DIR)

processor.save_pretrained(FINAL_MODEL_DIR)
print("Saved final merged model to:", FINAL_MODEL_DIR)

device = "cuda" if torch.cuda.is_available() else "cpu"
eval_model.to(device)

def transcribe_wav(wav_path):
    audio_array, sr = librosa.load(wav_path, sr=16000)

    inputs = processor.feature_extractor(
        audio_array,
        sampling_rate=16000,
        return_tensors="pt"
    )

    input_features = inputs.input_features.to(device)

    with torch.no_grad():
        predicted_ids = eval_model.generate(input_features)

    text = processor.tokenizer.batch_decode(predicted_ids, skip_special_tokens=True)[0]
    return text

# TEST FILE
sample_wav = "/content/drive/MyDrive/Youtube_Transcripts_Final/chunk_0004.wav"
print(transcribe_wav(sample_wav))